import { randomUUID } from 'node:crypto';
import { appPool, asTenant, insertRow, newId } from './rls-test-client.js';
import { cleanupTenantGraph, seedTenantGraph, type TenantFixture } from './rls-fixtures.js';

/**
 * Vector 2: cross-tenant WRITE. Under a session scoped to tenant A, try to
 * INSERT a row whose own `tenantId` column names tenant B - the
 * `WITH CHECK ("tenantId" = current_setting('app.tenant_id', true))` half
 * of each table's policy is what has to reject this (a spoofed tenantId in
 * the request body, an app-layer bug that forgot to stamp tenantId from
 * the authenticated session, etc.).
 *
 * A representative sample across the schema's different shapes, not
 * literally all tenant-scoped tables - unlike vector 1 (cross-tenant read),
 * which has to be exhaustive because a single mis-scoped SELECT is a real
 * data leak no sampling can rule out, every WITH CHECK clause here is
 * generated by the exact same migration pattern
 * (`"tenantId" = current_setting('app.tenant_id', true)`, verbatim, see
 * any *_row_level_security/accounts_payable_purchase_invoice/
 * purchase_credit_note migration) and vector 4 already structurally
 * confirms every one of the ~56 tenant-scoped tables has exactly this kind
 * of policy present. What could actually differ per table and go wrong is
 * "does this specific WITH CHECK actually fire", which this sample proves
 * across a root table with no FKs (companies), a leaf/child table two FKs
 * deep (purchase_credit_note_tax_lines), and the exact module from the
 * PurchaseCreditNote work (purchase_invoices/purchase_credit_notes).
 */
describe('RLS cross-tenant write rejection (WITH CHECK)', () => {
  let tenantAId: string;
  let tenantBId: string;
  let fixtureA: TenantFixture;

  beforeAll(async () => {
    tenantAId = randomUUID();
    tenantBId = randomUUID();
    fixtureA = await asTenant(tenantAId, async (client) => {
      await insertRow(client, 'tenants', tenantAId, { name: 'RLS Test Tenant A' });
      return seedTenantGraph(client, tenantAId, 'A');
    });
    await asTenant(tenantBId, async (client) => {
      await insertRow(client, 'tenants', tenantBId, { name: 'RLS Test Tenant B' });
    });
  });

  afterAll(async () => {
    await cleanupTenantGraph(tenantAId);
    await cleanupTenantGraph(tenantBId);
    await appPool.end();
  });

  // Asserts on the SQLSTATE (42501 = insufficient_privilege, what Postgres
  // raises for a WITH CHECK violation), not the error message text - this
  // server's locale renders it in Spanish ("el nuevo registro viola la
  // política de seguridad de registros..."), and asserting on a
  // human-readable string would make the test fragile to locale rather
  // than actually verifying the mechanism.
  async function expectInsertRejected(table: string, values: Record<string, unknown>): Promise<void> {
    let error: unknown;
    try {
      await asTenant(tenantAId, (client) => insertRow(client, table, newId(), values));
    } catch (err) {
      error = err;
    }
    expect(error).toBeDefined();
    expect((error as { code?: string }).code).toBe('42501');
  }

  it('rejects a root table row (companies) claiming another tenant', async () => {
    await expectInsertRejected('companies', { tenantId: tenantBId, name: 'Spoofed company' });
  });

  it('rejects a root table row (currencies) claiming another tenant', async () => {
    await expectInsertRejected('currencies', { tenantId: tenantBId, code: 'USD', name: 'Dólar' });
  });

  it('rejects a users row claiming another tenant', async () => {
    await expectInsertRejected('users', {
      tenantId: tenantBId,
      email: 'spoofed@test.local',
      passwordHash: 'x',
      role: 'OWNER',
    });
  });

  it('rejects a purchase_invoices row claiming another tenant', async () => {
    await expectInsertRejected('purchase_invoices', {
      tenantId: tenantBId,
      purchaseOrderId: fixtureA.ids.purchaseInvoiceId, // irrelevant - WITH CHECK fails first
      supplierId: fixtureA.ids.companyId,
      supplierName: 'x',
      supplierInvoiceNumber: 'SPOOF-1',
      supplierInvoiceDate: new Date(),
      currencyId: fixtureA.ids.currencyId,
      subtotal: 1,
      taxTotal: 0,
      total: 1,
      balanceDue: 1,
      createdByUserId: fixtureA.ids.userId,
    });
  });

  it('rejects a purchase_credit_notes row claiming another tenant', async () => {
    await expectInsertRejected('purchase_credit_notes', {
      tenantId: tenantBId,
      purchaseInvoiceId: fixtureA.ids.purchaseInvoiceId,
      supplierId: fixtureA.ids.companyId,
      supplierName: 'x',
      supplierCreditNoteNumber: 'SPOOF-NC-1',
      supplierCreditNoteDate: new Date(),
      reason: 'spoofed',
      currencyId: fixtureA.ids.currencyId,
      subtotal: 1,
      taxTotal: 0,
      total: 1,
      createdByUserId: fixtureA.ids.userId,
    });
  });

  it('rejects a purchase_credit_note_tax_lines row claiming another tenant', async () => {
    await expectInsertRejected('purchase_credit_note_tax_lines', {
      tenantId: tenantBId,
      purchaseCreditNoteId: fixtureA.ids.purchaseCreditNoteId,
      type: 'IVA_CREDITO',
      concept: 'spoofed',
      amount: 1,
    });
  });

  it('rejects a journal_entries row claiming another tenant', async () => {
    await expectInsertRejected('journal_entries', {
      tenantId: tenantBId,
      description: 'spoofed entry',
      createdById: fixtureA.ids.userId,
    });
  });

  it('rejects an invoices row claiming another tenant', async () => {
    await expectInsertRejected('invoices', {
      tenantId: tenantBId,
      customerId: fixtureA.ids.companyId,
      customerName: 'x',
      documentLetter: 'B',
      pointOfSale: '0001',
      number: 'SPOOF-B-1',
      currencyId: fixtureA.ids.currencyId,
      exchangeRate: 1,
      subtotal: 1,
      taxTotal: 0,
      total: 1,
      balanceDue: 1,
      issuedByUserId: fixtureA.ids.userId,
    });
  });
});
