import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { getTenantDb, PrismaService, withTenantContext } from '@plexo/database';
import { InventoryService } from '@plexo/inventory';
import { QuoteRequestService } from '@plexo/purchases';

interface ReplenishmentGroup {
  supplierId: string;
  lines: { articleVariantId: string; quantity: number }[];
}

function groupBySupplier(
  suggestions: { preferredSupplierId: string | null; articleVariantId: string; suggestedQuantity: number }[],
): ReplenishmentGroup[] {
  const bySupplier = new Map<string, ReplenishmentGroup>();
  for (const s of suggestions) {
    if (!s.preferredSupplierId) continue;
    let group = bySupplier.get(s.preferredSupplierId);
    if (!group) {
      group = { supplierId: s.preferredSupplierId, lines: [] };
      bySupplier.set(s.preferredSupplierId, group);
    }
    const existingLine = group.lines.find((l) => l.articleVariantId === s.articleVariantId);
    if (existingLine) existingLine.quantity += s.suggestedQuantity;
    else group.lines.push({ articleVariantId: s.articleVariantId, quantity: s.suggestedQuantity });
  }
  return Array.from(bySupplier.values());
}

export interface AutoReplenishmentResult {
  created: number;
  skippedAlreadyToday: number;
}

/**
 * Barrido diario (opt-in por fila, ver MinimumStock.autoReplenish /
 * InventoryService.listReorderSuggestions): crea un Pedido de Cotización
 * por proveedor para las sugerencias de reposición marcadas
 * `autoReplenish`, sin que nadie entre a la pantalla de Alertas. Mismo
 * patrón que ReceivablesSchedulerService (list_tenant_ids() +
 * withTenantContext por tenant, un fallo no aborta el resto).
 *
 * Atribuido al OWNER activo más antiguo del tenant - createdByUserId es
 * obligatorio en QuoteRequest y su numeración es por usuario (ver
 * PurchaseNumberingService), así que cada pedido automático consume UN
 * número de la serie personal de ese OWNER - decisión explícita con el
 * usuario (2026-08-21) en vez de inventar un actor "sistema" que no existe
 * en el modelo de datos hoy.
 *
 * Idempotencia simple, no merge de líneas: como mucho un pedido
 * auto-generado por proveedor por día - si ya existe uno creado hoy
 * (autoGenerated=true), se lo deja como está en vez de sumarle líneas
 * nuevas (evita la complejidad de mergear contra un documento que el
 * usuario capaz ya está mirando/editando). Un artículo que se vuelve
 * crítico más tarde el mismo día espera a la corrida de mañana - mismo
 * ritmo por lotes que usa Odoo para sus reordering rules.
 */
@Injectable()
export class InventoryReplenishmentSchedulerService {
  private readonly logger = new Logger(InventoryReplenishmentSchedulerService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly inventoryService: InventoryService,
    private readonly quoteRequestService: QuoteRequestService,
  ) {}

  @Cron(CronExpression.EVERY_DAY_AT_2AM)
  async autoReplenishForAllTenants(): Promise<void> {
    const tenants = await this.prisma.$queryRaw<{ id: string }[]>`SELECT id FROM list_tenant_ids() AS id`;

    for (const { id: tenantId } of tenants) {
      try {
        const result = await this.runAutoReplenishmentForTenant(tenantId);
        this.logger.log(
          `Tenant ${tenantId}: ${result.created} pedido(s) de reposición creado(s), ` +
            `${result.skippedAlreadyToday} proveedor(es) ya tenían uno hoy`,
        );
      } catch (err) {
        this.logger.error(`Failed auto-replenishment for tenant ${tenantId}: ${(err as Error).message}`);
      }
    }
  }

  /** Resuelve el OWNER y abre su propio contexto de tenant con ese userId -
   * usado sólo por el cron, que no corre dentro de ningún request. */
  private async runAutoReplenishmentForTenant(tenantId: string): Promise<AutoReplenishmentResult> {
    const owner = await withTenantContext(this.prisma, tenantId, () =>
      getTenantDb().user.findFirst({
        where: { role: 'OWNER', status: 'ACTIVE' },
        orderBy: { createdAt: 'asc' },
        select: { id: true },
      }),
    );
    if (!owner) {
      this.logger.warn(`Tenant ${tenantId}: sin ningún OWNER activo, no se puede atribuir un pedido automático`);
      return { created: 0, skippedAlreadyToday: 0 };
    }

    return withTenantContext(
      this.prisma,
      tenantId,
      () => this.runAutoReplenishmentForCurrentTenant(),
      owner.id,
    );
  }

  /** Core tenant-scoped: asume que el contexto de tenant (y un userId
   * válido en él) ya está activo - por el cron (arriba, con el OWNER) o
   * por un request HTTP ya autenticado ("Ejecutar ahora", con quien haya
   * apretado el botón - restringido a OWNER/ADMIN por el controller, así
   * que es un actor legítimo con numeración propia, sin necesidad de
   * buscar al OWNER en ese camino). Mismo criterio que
   * ReceivablesSchedulerService.runReminderSweepForCurrentTenant. */
  async runAutoReplenishmentForCurrentTenant(): Promise<AutoReplenishmentResult> {
    const suggestions = await this.inventoryService.listReorderSuggestions();
    const eligible = suggestions.filter((s) => s.autoReplenish && s.preferredSupplierId);
    const groups = groupBySupplier(eligible);
    if (groups.length === 0) {
      return { created: 0, skippedAlreadyToday: 0 };
    }

    const currency = await getTenantDb().currency.findFirst({ orderBy: { code: 'asc' } });
    if (!currency) {
      this.logger.warn('Sin ninguna moneda configurada, no se puede crear el pedido de reposición automática');
      return { created: 0, skippedAlreadyToday: 0 };
    }

    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);

    let created = 0;
    let skippedAlreadyToday = 0;
    for (const group of groups) {
      const alreadyToday = await getTenantDb().quoteRequest.findFirst({
        where: { supplierId: group.supplierId, autoGenerated: true, createdAt: { gte: todayStart } },
        select: { id: true },
      });
      if (alreadyToday) {
        skippedAlreadyToday += 1;
        continue;
      }
      await this.quoteRequestService.create(
        {
          supplierId: group.supplierId,
          currencyId: currency.id,
          notes: 'Generado automáticamente por reposición de stock (mínimo configurado en Inventario).',
          lines: group.lines,
        },
        true,
      );
      created += 1;
    }
    return { created, skippedAlreadyToday };
  }
}
