-- AlterTable
ALTER TABLE "minimum_stock" ADD COLUMN     "autoReplenish" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "quote_requests" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

